import '../models/models.dart';

/// 示例菜谱数据
class SampleData {
  static List<Recipe> getSampleRecipes() {
    return [
      _tomatoEggs(),
      _kungPaoChicken(),
      _steamedFish(),
    ];
  }

  /// 番茄炒蛋
  static Recipe _tomatoEggs() {
    return Recipe(
      id: 'recipe_tomato_eggs',
      name: '番茄炒蛋',
      description: '经典家常菜，酸甜可口',
      estimatedMinutes: 15,
      servings: 2,
      difficulty: '简单',
      tags: ['家常菜', '快手菜', '下饭菜'],
      ingredients: [
        Ingredient(id: 'ing_1', name: '鸡蛋', quantity: 3, unit: '个'),
        Ingredient(id: 'ing_2', name: '番茄', quantity: 2, unit: '个'),
        Ingredient(id: 'ing_3', name: '葱', quantity: 1, unit: '根'),
        Ingredient(id: 'ing_4', name: '盐', quantity: 3, unit: '克'),
        Ingredient(id: 'ing_5', name: '糖', quantity: 5, unit: '克'),
      ],
      steps: [
        Step(
          id: 'step_te_1',
          recipeId: 'recipe_tomato_eggs',
          action: '准备食材',
          description: '番茄切块，鸡蛋打散加少许盐，葱切葱花',
          durationSeconds: 180,
          resourceType: 'cuttingBoard',
          parallelLevel: ParallelLevel.focused,
          requiresCleaningAfter: false,
          orderIndex: 0,
        ),
        Step(
          id: 'step_te_2',
          recipeId: 'recipe_tomato_eggs',
          action: '滑炒鸡蛋',
          description: '热锅冷油，倒入蛋液快速划散，蛋液凝固即盛出',
          durationSeconds: 60,
          dependencies: ['step_te_1'],
          resourceType: 'wok',
          parallelLevel: ParallelLevel.focused,
          requiresCleaningAfter: true,
          orderIndex: 1,
        ),
        Step(
          id: 'step_te_3',
          recipeId: 'recipe_tomato_eggs',
          action: '炒番茄',
          description: '锅中加少许油，放入番茄块翻炒出汁',
          durationSeconds: 120,
          dependencies: ['step_te_2'],
          resourceType: 'wok',
          parallelLevel: ParallelLevel.focused,
          requiresCleaningAfter: false,
          orderIndex: 2,
        ),
        Step(
          id: 'step_te_4',
          recipeId: 'recipe_tomato_eggs',
          action: '合炒调味',
          description: '倒入炒好的鸡蛋，加盐和糖调味，翻炒均匀',
          durationSeconds: 60,
          dependencies: ['step_te_3'],
          resourceType: 'wok',
          parallelLevel: ParallelLevel.focused,
          requiresCleaningAfter: false,
          orderIndex: 3,
        ),
        Step(
          id: 'step_te_5',
          recipeId: 'recipe_tomato_eggs',
          action: '出锅装盘',
          description: '撒上葱花，装盘即可',
          durationSeconds: 30,
          dependencies: ['step_te_4'],
          parallelLevel: ParallelLevel.parallel,
          requiresCleaningAfter: false,
          orderIndex: 4,
        ),
      ],
    );
  }

  /// 宫保鸡丁
  static Recipe _kungPaoChicken() {
    return Recipe(
      id: 'recipe_kung_pao',
      name: '宫保鸡丁',
      description: '经典川菜，麻辣鲜香',
      estimatedMinutes: 25,
      servings: 2,
      difficulty: '中等',
      tags: ['川菜', '下饭菜', '经典'],
      ingredients: [
        Ingredient(id: 'ing_kp_1', name: '鸡胸肉', quantity: 300, unit: '克'),
        Ingredient(id: 'ing_kp_2', name: '花生米', quantity: 50, unit: '克'),
        Ingredient(id: 'ing_kp_3', name: '干辣椒', quantity: 10, unit: '个'),
        Ingredient(id: 'ing_kp_4', name: '花椒', quantity: 10, unit: '克'),
        Ingredient(id: 'ing_kp_5', name: '葱', quantity: 2, unit: '根'),
        Ingredient(id: 'ing_kp_6', name: '姜', quantity: 1, unit: '块'),
        Ingredient(id: 'ing_kp_7', name: '蒜', quantity: 3, unit: '瓣'),
      ],
      steps: [
        Step(
          id: 'step_kp_1',
          recipeId: 'recipe_kung_pao',
          action: '鸡肉切丁腌制',
          description: '鸡胸肉切丁，加料酒、生抽、淀粉腌制15分钟',
          durationSeconds: 300,
          resourceType: 'cuttingBoard',
          parallelLevel: ParallelLevel.background,
          requiresCleaningAfter: true,
          isPrepRequired: true,
          orderIndex: 0,
        ),
        Step(
          id: 'step_kp_2',
          recipeId: 'recipe_kung_pao',
          action: '准备配料',
          description: '切葱段、姜片、蒜末，干辣椒切段',
          durationSeconds: 180,
          dependencies: ['step_kp_1'],
          resourceType: 'cuttingBoard',
          parallelLevel: ParallelLevel.parallel,
          requiresCleaningAfter: false,
          orderIndex: 1,
        ),
        Step(
          id: 'step_kp_3',
          recipeId: 'recipe_kung_pao',
          action: '调宫保汁',
          description: '生抽、醋、糖、淀粉调成料汁备用',
          durationSeconds: 60,
          parallelLevel: ParallelLevel.parallel,
          requiresCleaningAfter: false,
          orderIndex: 2,
        ),
        Step(
          id: 'step_kp_4',
          recipeId: 'recipe_kung_pao',
          action: '炸花生米',
          description: '冷油下锅，小火炸至金黄捞出',
          durationSeconds: 180,
          resourceType: 'wok',
          parallelLevel: ParallelLevel.focused,
          requiresCleaningAfter: false,
          orderIndex: 3,
        ),
        Step(
          id: 'step_kp_5',
          recipeId: 'recipe_kung_pao',
          action: '滑炒鸡丁',
          description: '热油滑炒鸡丁至变色盛出',
          durationSeconds: 120,
          dependencies: ['step_kp_1', 'step_kp_4'],
          resourceType: 'wok',
          parallelLevel: ParallelLevel.focused,
          requiresCleaningAfter: true,
          orderIndex: 4,
        ),
        Step(
          id: 'step_kp_6',
          recipeId: 'recipe_kung_pao',
          action: '爆香调料',
          description: '爆香花椒、干辣椒、葱姜蒜',
          durationSeconds: 60,
          dependencies: ['step_kp_5', 'step_kp_2'],
          resourceType: 'wok',
          parallelLevel: ParallelLevel.focused,
          requiresCleaningAfter: false,
          orderIndex: 5,
        ),
        Step(
          id: 'step_kp_7',
          recipeId: 'recipe_kung_pao',
          action: '合炒出锅',
          description: '倒入鸡丁、料汁翻炒，最后加花生米出锅',
          durationSeconds: 90,
          dependencies: ['step_kp_6', 'step_kp_3'],
          resourceType: 'wok',
          parallelLevel: ParallelLevel.focused,
          requiresCleaningAfter: false,
          orderIndex: 6,
        ),
      ],
    );
  }

  /// 清蒸鱼
  static Recipe _steamedFish() {
    return Recipe(
      id: 'recipe_steamed_fish',
      name: '清蒸鱼',
      description: '鲜嫩可口，原汁原味',
      estimatedMinutes: 20,
      servings: 3,
      difficulty: '简单',
      tags: ['粤菜', '清淡', '蒸菜'],
      ingredients: [
        Ingredient(id: 'ing_sf_1', name: '鲈鱼', quantity: 1, unit: '条'),
        Ingredient(id: 'ing_sf_2', name: '葱', quantity: 2, unit: '根'),
        Ingredient(id: 'ing_sf_3', name: '姜', quantity: 1, unit: '块'),
        Ingredient(id: 'ing_sf_4', name: '蒸鱼豉油', quantity: 30, unit: '毫升'),
      ],
      steps: [
        Step(
          id: 'step_sf_1',
          recipeId: 'recipe_steamed_fish',
          action: '处理鱼',
          description: '鱼去鳞去内脏，两面划几刀',
          durationSeconds: 300,
          resourceType: 'cuttingBoard',
          parallelLevel: ParallelLevel.focused,
          requiresCleaningAfter: true,
          orderIndex: 0,
        ),
        Step(
          id: 'step_sf_2',
          recipeId: 'recipe_steamed_fish',
          action: '切葱姜丝',
          description: '葱切丝，姜切丝备用',
          durationSeconds: 120,
          resourceType: 'cuttingBoard',
          parallelLevel: ParallelLevel.parallel,
          requiresCleaningAfter: false,
          orderIndex: 1,
        ),
        Step(
          id: 'step_sf_3',
          recipeId: 'recipe_steamed_fish',
          action: '蒸鱼',
          description: '鱼放入盘中，铺上姜丝，大火蒸8-10分钟',
          durationSeconds: 600,
          dependencies: ['step_sf_1', 'step_sf_2'],
          resourceType: 'steamer',
          parallelLevel: ParallelLevel.background,
          requiresCleaningAfter: false,
          orderIndex: 2,
        ),
        Step(
          id: 'step_sf_4',
          recipeId: 'recipe_steamed_fish',
          action: '淋热油',
          description: '取出鱼，倒掉汤汁，铺葱丝，淋热油和蒸鱼豉油',
          durationSeconds: 60,
          dependencies: ['step_sf_3'],
          resourceType: 'wok',
          parallelLevel: ParallelLevel.focused,
          requiresCleaningAfter: false,
          orderIndex: 3,
        ),
      ],
    );
  }
}
